name: e2e
on: [push, pull_request]

jobs:
  e2e-tests:
    name: Browser e2e tests
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18.x
      -
        name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      -
        name: Setup Playwright
        uses: microsoft/playwright-github-action@v1
      -
        name: Build and run tests
        run: |
          npm install
          npx playwright install --with-deps
          make test-e2e

